name: deploy to lambda

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Dependencies
        run: |          
          go get -v ./cmd/main.go

      - name: Build
        run: go build -v ./cmd/main.go

      - name: Zip
        run: zip function.zip main

      - name: Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: testGo
          zip_file: function.zip
